### ISSUE TITLE
Testing Workflow?

### ISSUE THREAD

**Issue by yewscion** [dzaima/BQN#12]
I see the `/tests/` directory in this repo, but no way (short of manually feeding the files one by one into the jarfile and checking their result) to actually run them.

Could the expected workflow for testing the jarfile be put into a script similar to `/build`?

**Comment by dzaima** [comment]
`test/test` is a BQN script that runs the tests. But some tests fail currently as this repo is mostly on just enough life support to be able to bootstrap CBQN.

**Comment by yewscion** [comment]
Copy that, I can likely figure out which ones those are and comment them out, though perhaps I can help them to succeed/be removed in the repo itself, once I know more about BQN etc.

**Comment by yewscion** [comment]
I was actually able to make all of the tests pass, somehow. So, resolving.
