### ISSUE TITLE
Add `/bin/dbqn` script to repo?

### ISSUE THREAD

**Issue by yewscion** [dzaima/BQN#13]
The following is mentioned in `readme.md`:

>Adding the following to `~/bin/dbqn` will make hashbangs like `#!/usr/bin/env dbqn` execute dzaima/BQN:
>```bash
>#!/bin/bash
>
>java -jar /path/to/dzaima/BQN/BQN.jar -f "$@"
>```

Would it be possible to include an example file in this repo, instead of relying on the manual creation of the script by the user? Perhaps including `./BQN.jar` as the default location of the jarfile, or something similar? 

Currently the file needs to be created during packaging, which makes maintaining that package more difficult.

**Comment by dzaima** [comment]
That mostly already is the file `./BQN` (except the `-f` part, which is only necessary if you want to execute files whose name starts with a dash); I guess `java -jar "$(dirname "$(readlink -f "$0")")/BQN.jar" "$@"` could also be used to allow it being invoked from everywhere, but then you can't move it to `/usr/bin/` or whatever without also moving `BQN.jar` there.

**Comment by yewscion** [comment]
That makes sense. 

I dunno what the 'right' choice is; however, I'm packaging CBQN for GNU/Guix (which requires things to be built from source, and so requires dbqn) and currently have a hardcoded script (that uses `/usr/share/java` as the expected location for the jarfile) inside of the package definition. 

I'll leave it like that for now, but ideally it would just be a substitution needed on a pre-existing file, instead of creating one from scratch during the packaging.

**Comment by yewscion** [comment]
Nevermind, I misunderstood. I will instead simply use the abovementioned `./BQN` script as the base.
