### ISSUE TITLE
Non-determinism in Build Process

### ISSUE THREAD

**Issue by yewscion** [dzaima/BQN#14]
Hello,

I am reported the discovery of a non-determinism issue in the dbqn source code.

I believe the issue lies here:

```
src/BQN/types/callable/builtins/fns/EpsBuiltin.java:45:71:    if (w.ia>20 && x.ia>20) { // TODO these (and in ⊐) shouldn't be random numbers
```

I don't know enough about how the source code currently works to fix this myself, but I wanted to report this upstream now, as I am submitting this package as a dependency of CBQN to GNU Guix tonight.

GNU Guix adheres as best as possible to the [Reproducible Build](https://reproducible-builds.org/) philosophy, and so non-determinism is an issue. However, so long as it is reported, it shouldn't prevent the inclusion of CBQN in the official Guix repo in the first place.

**Comment by dzaima** [comment]
that line is about me picking some arbitrary numbers instead of actually profiling & deciding which ones are the best choices.
For the actual cause - it seems Java encodes the current date in class files.

**Comment by yewscion** [comment]
Ahhh, okay. Interesting. (I wasn't aware of that; Is that standard behavior?)

I wonder if there's a way to turn that off, perhaps with a flag to javac?

**Comment by dzaima** [comment]
it seems that it's just the files in the jar (as jar files are just zip files) just have their "last modified" date kept, so the `jar` invocation is actually what to look at. There doesn't seem to be any option for it, but maybe it'd be possible to manually set the the last modified time before `jar`?

**Comment by yewscion** [comment]
Oh, interesting! That's a much more solvable issue, then. I'm sure there is a fix for that already in GNU Guix, somewhere. I'll start reading through other packages. Thank You for helping me locate the issue!

**Comment by dzaima** [comment]
even with `touch -c -d '1970-01-01T00:00:00.000000000' -- $(find)` before the `jar` invocation, a different result is produced every time; even with the same `classes` folder, `jar` produces a different thing on each invocation.
But yeah it's a generic java issue, nothing special to dzaima/BQN.

**Comment by yewscion** [comment]
If You are curious, here is one way the Guix maintainers found to work around this issue:

https://git.savannah.gnu.org/cgit/guix.git/tree/guix/build/ant-build-system.scm#n198
