### ISSUE TITLE
insert (˝) not found on android keyboard

### ISSUE THREAD

**Issue by GamingKing2436** [dzaima/BQN#15]
i checked every key direction and layer (there seem to only be 2 aside from shift) and it's not there, in it's place there's (○). i also see references to fold in data/app. you also can't type it using the K(eyboard) button, you have to copy and paste.
![Screenshot_20231123_122353](https://github.com/dzaima/BQN/assets/48329218/6887e7d8-2fe7-43fc-8f78-68ee9beda705)

**Comment by dzaima** [comment]
The apk hasn't been rebuilt from when it was added (messy to do with Processing/android SDK issues; the issue about keyboard input unicode not working is a Processing issue too), I don't bother supporting it anymore. My usual way of running BQN on my phone now is CBQN within termux.

**Comment by GamingKing2436** [comment]
nevermind i finally figured out how to build from source (i was just bad at reading numbers) and it's wonderful
also thanks for the cbqn on termux tip i will try that too
